### ISSUE TITLE
slide show from local files?

### ISSUE THREAD

**Issue by corporate-gadfly** [chrisdavies/markdown-slides#1]
Is it possible to have a slide show when browsing the local file system? E.g., `file:///Users/someuser/abcd.md`?

My experience, so far, shows that the green icon never shows up. I ended up installed `http-server` in node.js and then browsing to `http://localhost:8080/`.

Thoughts?

**Comment by chrisdavies** [comment]
Yep! You go to `chrome://extensions`, find the `markdown slideshow` extension, and check the `Allow access to file urls` option. (It was a pain to get that working, so I'm glad someone's using it!)
